apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: retracedhq/retraced-local
      context: ./
      docker:
        dockerfile: ./deploy/Dockerfile-slim
  platforms:
    - linux/amd64
    - linux/arm64
  local:
    push: false
manifests:
  kustomize:
    paths:
      - ./kustomize/overlays/dev
