data_dir = "/var/lib/vector/"

[api]
enabled = true

# The data source that Vector will collect logs from
[sources.webhook]
type = "http_server" # The protocol to use
address = "0.0.0.0:9000" # The address to bind to
healthcheck = true # Enable built-in health checks
body_size_limit = "1mb" # Maximum size of request body
auth.password = "${EXPORT_WEBHOOK_PASSWORD}"
auth.username = "${EXPORT_WEBHOOK_USERNAME}"

# The transformation(s) to apply to each event for s3
[transforms.iceberg_transform]
type = "remap"
inputs = [ "webhook" ]
source = """
# Set the values of the output object
. = parse_json!(parse_json!(.message).message)
"""

[sinks.iceberg]
inputs = ["iceberg_transform"]
type = "http"
uri = "http://iceberg-server:9090/ingest/bulk"
method = "post"
encoding.codec = "json"
batch.max_events = 500
request.concurrency = "adaptive"
healthcheck.enabled = true
healthcheck.uri = "http://iceberg-server:9090/"