apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-api
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap
          image: retraced-api
      containers:
        - name: api
          image: retraced-api

