version: "3.8"

services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=retraced
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=retraced

  elasticsearch:
    image: elasticsearch:7.8.0
    volumes:
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
