apiVersion: v1
kind: ConfigMap
metadata:
  name: retraced-elasticsearch
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    http.host: 0.0.0.0

    http.port: 9200
    http.cors.allow-origin: "chrome-extension://jopjeaiilkcibeohjdmejhoifenbnmlh"
    http.cors.enabled: true
    http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    http.cors.allow-credentials: true
