apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: retraced-elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: estransport
  selector:
    app: elasticsearch
